### ISSUE TITLE
Loss and Regularizer

### ISSUE THREAD

**Issue by crackhopper** [crackhopper/TFS-toolbox#11]

**Comment by mingzailao** [comment]
HAHA, 
https://github.com/crackhopper/TFS-toolbox/tree/feat_loss_11
sorry :(  
before "#“ should have a space?

**Comment by crackhopper** [comment]
yep, should have a space.  if you think you have finished the feature, just send a pull request.

**Comment by crackhopper** [comment]
if you finished the codes, make a pull request please.

**Comment by mingzailao** [comment]
1. For __str__, i think it should be implemented at last.
2. for loss, i modify the loss to compute the loss for each instance and return the list of each instance's loss. is it OK? or mean loss is better?

**Comment by crackhopper** [comment]
good work.
